apiVersion: v1
kind: Secret
metadata:
  name: {{ include "student-survey.fullname" . }}-backend-secret
  labels:
    {{- include "student-survey.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.database.url | quote }}
